image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
- build

build-master:
  stage: build
  script: |
    for container in $(ls -d */ | sed 's^/^^g') ; do
      docker build --pull -t "${CI_REGISTRY_IMAGE}/${container}" ./${container}
      docker push "${CI_REGISTRY_IMAGE}/${container}:latest"
    done
  only:
    - master

build-tags:
  stage: build
  script: |
    container=$(echo ${CI_COMMIT_REF_NAME} | awk -F / '{print $1}')
    version=$(echo ${CI_COMMIT_REF_NAME} | awk -F / '{print $NF}')
    echo "Building container '${container}' with version '${version}' from branch ${CI_COMMIT_REF_NAME}"
    docker build --pull -t "${CI_REGISTRY_IMAGE}/${container}:${version}" ./${container}
    docker push "${CI_REGISTRY_IMAGE}/${container}:${version}"
  only:
    - tags
