image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script: |
    for container in rabbitmq squid nginx ; do
      docker build --pull -t "${CI_REGISTRY_IMAGE}/${container}" ./${container}
      docker push "${CI_REGISTRY_IMAGE}/${container}"
    done
  only:
    - master

rabbitmq:
  stage: build
  script: |
    container=rabbitmq
    docker build --pull -t "${CI_REGISTRY_IMAGE}/${container}:${CI_COMMIT_REF_SLUG/${container}-/}" ./${container}
    docker push "${CI_REGISTRY_IMAGE}/${container}:${CI_COMMIT_REF_SLUG/${container}-/}"
  only:
    - /rabbitmq\//

squid:
  stage: build
  script: |
    container=squid
    docker build --pull -t "${CI_REGISTRY_IMAGE}/${container}:${CI_COMMIT_REF_SLUG/${container}-/}" ./${container}
    docker push "${CI_REGISTRY_IMAGE}/${container}:${CI_COMMIT_REF_SLUG/${container}-/}"
  only:
    - /squid\//

nginx:
  stage: build
  script: |
    container=nginx
    docker build --pull -t "${CI_REGISTRY_IMAGE}/${container}:${CI_COMMIT_REF_SLUG/${container}-/}" ./${container}
    docker push "${CI_REGISTRY_IMAGE}/${container}:${CI_COMMIT_REF_SLUG/${container}-/}"
  only:
    - /nginx\//